# Generated by Django 3.2.9 on 2021-12-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facerecognition',
            name='C_parameters',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='facerecognition',
            name='T_parameters',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='facerecognition',
            name='V_parameters',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
