# Generated by Django 3.2.9 on 2021-12-15 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211214_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facerecognition',
            name='C_parameters',
        ),
        migrations.RemoveField(
            model_name='facerecognition',
            name='T_parameters',
        ),
        migrations.RemoveField(
            model_name='facerecognition',
            name='V_parameters',
        ),
    ]
